basePath: /
host: localhost:1323
info:
  contact: {}
  description: This is a sample server for using Swagger with Echo.
  title: Swagger Example API
  version: "1.0"
paths:
  /authen/signup:
    post:
      consumes:
      - application/json
      responses: {}
swagger: "2.0"
