name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.2'

    - name: Build
      run: go build -v ./

    - name: Build Docker Image
      run: |
        docker build -t dewlonger/todo-api:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: Dewlonger15@gmail.com
        password: Dewsmaller1*

    - name: Push Docker Image
      run: |
        docker push dewlonger/todo-api:latest

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.2'

    - name: Test Services
      run: go test -v ./test/service

  